### PR TITLE
helpers for markup - like in coffeecup

### PR DESCRIPTION
**Pull request by chethiya**
I only looked at how this will fit in with markup method.

### CODE REVIEW

**Comment by vpj** [comment]
Do you think we should use this or have a separate API to register helper functions?
I feel it might make more sense to register helpers once without having to parse `helpers` every time.
What do you think?

**Comment by chethiya** [comment]
This is how I use it. I have multiple reports each having it's own templates and helpers. When I need to generate reports I go through each report and generate the HTML using Weya.markup(). 

If subsequent calls to Weya.setHelpers() removes old helper method, then there isn't much gain in this case. 
Even if multiple calls to Weya.setHelp() persists old helper methods, there is no guarantee that there won't be helper method name duplicates.

Is it a good idea to generate multiple instances of Weya with different helper functions?

**Comment by vpj** [comment]
In such scenarios I call those helper functions from the template itself.
For example,

**Example**

``` coffeescript
class Form
 helperForm: (title, innerForm) ->
  @form ->
   @legend title
   innerForm.call this

 render: ->
  Weya context: this, ->
   @$.helperForm.call this, 'User registration', ->
    @input type: email
```

Isn't that a lot simpler?

**Comment by chethiya** [comment]
I really don't mind using that trick.

In my case there are multiple calls to the same helper methods inside the template (e.g. custom defined table, row, column elements). I prefer having those helper methods in `this` object rather than having to call them through Function.call() method. 

If that's the case isn't there any other case where Weya needs to support helper methods?

**Comment by vpj** [comment]
Got the point. Will merge this pull. We will also need to support permanent helpers too.

**Pull request merged**
